env:
  global:
    - secure: fFnDdGtTM4AzOtrleh3ort+Q9hA5Kf9J0wxhX/LG0wxaVf7QlXv5PmtXZlusebF2eL1GKV1JQorrE5wv+V340nMi6PggX6c4hywIF8Q/ePOsBxswS7exeHoBvOud85wOxqrKgDM56r8MO33qeMMk57bAhGM3/GYWP+Kku8xRNke47Y8+BX+AS0M2nd3r+wMv0mSpyfahlyHjR9ZMN1t6CZY4z+LAlYCGOpgXT00bcAwNnFM1HII2qZ+jgc4Nv6KdLD+J9gE6s11BYrkD86kDq+NHgZWqXLHulJIzLkdYHUo+GaKOXTC+MlczzZ9pAfonzYfejFFz8FtGG6QC6q+vyTMD60lP8Rw7c8fGztTWwJOJWOzjlNFM/xdRqx4QjdP9gee7tuWZFSaUsGCgFSejAXtSk/nK6yjjFPKOUdljoY3TL7LqY84CjGGdzMFDACAry+pVobHsCH9fMB23hJDRwKVLzMKNlxaXE4PwMAJ37+VIxc7kqluYmzhLrSII3CMkaxZ+EBrW68P29fm/gyvx0NLtmU8bfVi/IQEnYI9wGsZcnwj9U/ArioacfPFbq9FuUv9Xwr7WHV71NAghYrIj1csqz5eW+7Kyhvm7plwcA82O0DQgW4DuNVGuTu9Qb4JaW+raMoS0WMi6c+bsBygjZ9OdYCcLWIDRCPo/Ge3Ry+A=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/BadIPs.com_KEY
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
