env:
  global:
    - secure: ia21y03yuSQAraTM1oqGWB2iD/b8BKqGRRIKxHY7YSeKOWniUM/hpJOt9Mwto2RaiBsRC4/bfPePDReWskp8R5qnxBq1EmsNxJFZ8M8++P+9PhtZroxrV1XklBo53J/49d7IigRUYF2LVb7CCpCdoAcI+2djHNKqPPzcDYpIRwfb+xYcZfw/NQ6sQNcJTfhe/W1JxR1amAmjdlsGTkqIGA6f/0DxABs9gjMH0AZTofU+Y9cUvX5DnVPvowwQMCd6tE6aiU3kIBWw0aWfft2vcwQEtOK9TR8mphM7KOyaD3eB6aZfWfTsqHod4auLXoyZucukzwgCb0Y7XnTr+9/tiJ2gRjmkmlFl4OuP5NYU1/Px9P5HokKPOPz6fTpLSl4LZlrzdjgqOHU57eoZKgE6Fuvg4f6ILJq4BXdbXp+FmixAouU1Qb2uLJdF+Ia891tz0eCO2vVPcpf8HNe0QR5tkBw0eJ4m782iLquJjYiYh+rPE3x6BOmq8J3l5CytLzKK2ka5CXvKwqEigRnmds2mfyof0/7aKoWcYMg92/kIOeNm+dIwVVfs5NKlM5ohPNSAmNrq6Vlo8qgSs7BrWBhWPKNtHvbYT7JtXXeHpIEXSHb00l9tlvk0BFDD8wCQ+xv7PIXB+6I10CSS9Ydmht3/7SyAq2BhPstpdYihwD4KMIw=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/BadIPs.com_KEY
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
