env:
  global:
    - secure: fvdtEMJnGqt+6SG/h33KavoLdd3y/8r2TnaOp/h2u8iiWVohyFNUvG9pB9RRC53wmgywDSewjRJxa5E64yQD79UkL2slCBmVeZk9SA2L36hJBAhLP/jBNia+/GNZJoV0Ks4Rs7kOuZTx2hBYqFtt43kBPWS/xp8Y1TKwrkvCVYbSE8AfGCoOxYcKaYBIsmJd8Y75EYDtF3n+MpjLLdHOUpvec/Gh6uoJu+iY5VaY3DLhuUwu1p2oqz79l/cmOPdQD7sgw9b+OO/vPaWrIzmX64T/fm/JMhY0SC/AZuZLdmCr87ZGsKmcuwJtTYn57FBwrCVHvckTHLPfUsVf+RwF5MgbjrRiXDvoyNCSdt+6CKM3quMCdN8Zvzhqmxv8PykRHGdxXBw3ikmnWMrW1gdImGVfVNbTyQky9OeOym4vRSyWunYksxsx9A8UtbBxxit5BogkCj++nmyXMAOXHKLb3ocTWaE/KALV6+/g/dQankG46BP9zQ4ZdtIVSNHTIgJBGeCYo5MiVq/YIRoCn7oGClYwhtzpW8m6RYrjYivyoDQfJnrh9aePPo4BBOb+jagLBC3Lt/Rkbw9a4D+Ms6IUP9kd0IWvnzP0toJ4UeitCwgUXjGajdDvBbZ/wpF4uEq80Y00+KKxkpX5PjKml95CJRuvoS5QMCftYmcAid87EFc=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/BadIPs.com_KEY
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
