env:
  global:
    - secure: YYmah+GbIPfPR2dv+hkaqj2mWxC9V+zaET/fvf+e0v2S1nUwOuOZpsqIoe65DUcqytxUgbgyfS4/Fa/zpOftYURQi52vS50hlJ8mj039HiM9sXgD/iVSkVBfUzxYsdkuVg71lPbkq3QwAtMsB6IDTrPXdoWu2TUKvEQRjYBf8vkbwA5DOEZI3F+8JWxp9iwg56/gnXM34/no+GLeHL1gtsS/K7O2UNZtXFlvj+KIr99xgqciO9lAWDL3iPcjT9NcADcPt0tD0Q7aPeIBF5kgFNPg4brBoA+Uo4EhAcdvsR6UR0cPjEkppfpNiUgBSCPGqSoG5hAx7Qc2EswSOdumF4a6FdpmfIZJ9Bk/OImOcKWHath3cR59BLEUixPiLfhokAzYr3iFnkJvH6zXLC+JSTGTyiSU/3WDvo1Z/YVwKk+Dnm31PIiNzFn6LAOJlh6OktS6pnJLkB0uta+U98ZvMvG8kgOYI4ffMXBJa/oksPOiEWRQzoTUu6Mp8N/prvHTykpg8a31NHDnjiXvdABGjor+BaSJZ+GZJDwmN5o1dWg5lekoVc1fh3SxcSGGyFfBmTo5NebhnbdT2BSXfdaRdX+IIAulpE1S0vMiLmgtGO/p5MgzUIwN4Rq+KpcJ+mL4v42+AX/V/hKDOuBJzH5aA9RCXayZHHa/Vbblq2NQd/4=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/BadIPs.com_KEY
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
