env:
  global:
    - secure: U48NHaWiMOXZUtscCA0JRg6GM68TOgpvzoj+DfH7N5fxBTkVwJ+N7TlKmTlNje2UqbErpj8CwFnc4r6AYVJZ4XfbhnTM3/I6wzVgCRqZz58ddjiHMV/tkzKNI1ayKPAiXvMJx6n7ySNQIMeHEo5Q5fvEpxWVR+lGoa/KJmmeTcuDABULOcn3OjlGnZiK3Q4ph3WHyduU0IgvGxpjgRpvPTQm14xnC5pu7HkQXWJr2pHZW2XoXZBVJQXtj599+Z7VBS85H5bK4AwB6D1S+uWuh+HK4Ip4XEk1ncY/+PMvklhMzs9rLS8+KNZb/OPO2h0aGkx6iGgI/3mw433SLtcJY4hEekt4g/anqrFIgRSKI5Ysleuie16P/f9OYpp4sqiy2jcnVGs/YIL67VqH9Es0Gn3T/dk6A1YtX0jwSc++uAGTe8nl+a9/eQTi2gfDY+CnzVlf6K3akJ2idww0S3MdJU0Oay6yGwNWOuvlTM38zAsw4aUSLXBqidl0LPywjXAqmHBgFNpSLCvgKQTHZbmtjcU+OI+CSFc6ZVDUy74u9vDYl8m6v2mFOrFFjhj8P9qNwW2bSgEV0m0l+aReuP6JJqDJSmUSo6m0V8+7MXKGlF21KUck+Wyvxtw6UEjeanEIdu5As0JhCrcFQ1+xW9oSFwevzqKRaGGL6BPTo5iw54s=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/BadIPs.com_KEY
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
