env:
  global:
    - secure: V0CdfeYnYkGxLMH99c28fbH3qhD7drNJTfkNEvGlUoX3xcv/JE5sFjo1/kbB03Iq4/8pGB0xzKOzjj0zp07KS88bvLCdRAihUEQYL/m3ZbXNtKMMYEQ9r5YHf0U8LfspZv8oIo+8+DXrsnCvFeX9eqi/pru7Ge0IaVVrnI1ZkAG0ceXSEOJRGxk16f6ENOoBQzNMJgBSTJe+SdutTtF58sq5eCQJwttVUmriV8rsgwNPxxBIEOkSWlBMDE3bSeQOShP8OAJYMxIiRlwxnAX0oRfgneZDyCruPjc+IEWgrx5GlLfHnuMuEzylSweMSbu+LB719QrVWSwKVaJ3kdW+qCh6ac+WoN2b6C+4OpcyY30+VOnCg6kixms0KuWfk67ABDFWLImJaU2QUNjdP1lcXwacDC7tQ4LPcmkusH1UWeM94csc2WtZpS8ZtkxzbAZKn8P1YRnkdqpVEBheJl8Gl8kgotjOh4tmOzI4NgnW+Qw9k1fEeoJHPNm66LG2iT0VOQL8NBvicc7She5OBwdr70cU1DEoFr8xnYfaUBqALngKfBxNuCHo+CrmBmvIur9CVnMRAkQYSwXfWwLymOM4jAvupUTI/RLCYBqFW70ZduRuviL+inkqHYxbkwhGD0a4wVOmvE/YtBNBGvl89rwURWQjF8XaPQT7Woet/uDrkeA=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/BadIPs.com_KEY
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
