env:
  global:
    - secure: kV9fO63N9pb1g8gYye7CaqOCnfcqni6ejvvK0IlBfUFbJPqLnWow3YNKo3LALG5jnijY+dtXyqndtr8rIQ6emDUj0+oKem5/6WEfQ1SbYi4tZ8ONoyeWk/K79E9pyrH/IjjC3klFIY23hi/IoD0wUlXCiQQzmh1h0ve9ntgOCW+e6P/vlcnvCx2453hFJQvF1dxTCs43M36sWMivvcJ1mk/yrfjS2SPYGhH5PSRHygSgNx2jYNsR8y0PqeLUjbqy+Tnt5nBxkS4ttgTYdwy/MlKdWOasZopUXVWvz0WAV83dydpLu0BnklEku3R+vwl1FvJT/PeGln31zt2BJz+E0W+P6qa86iZPUtdU8J5MLzXY2wJ081rzY/J0rzuYKrki3+eJ+hDumkG0yX+MuK1OKsu9bZxgPOdWMldQIeTO+dmrZHuQWfbZM15eX2orxH0bbYxFUqqFwYYtmWut0tsMKR2Q0PyvUKg39hThruQ82oekS03GjAlJPgCjuxJaux/NMtXA3wOtBbfWJbTWPu7/jdE0iaYUWSefKmJa6jnjsqBkR56dbWI32fomI/6WzlIZuxVaC5Vmf5i2lKU68/l8yMWoAOvv18QLzRUN45aVXlsVrsGT4vEXP1IniXybL6N6ibbzrAYMenVbacVaGwDKfGi+tFBUYhLOi9UEwSe/tqQ=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/BadIPs.com_KEY
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
