env:
  global:
    - secure: AyE+9fnHo6uH9HGRURlwqiRTCDMUNLEdKGqAI20FupDaMmuj/hLOmI5oPp7vEo3/lhBbhjbgUWo15GPESd5PJEwjUkvgm7/C9JjJywvjnuqmh0YEBJvoIdDIatRZ8AX50f5VQUKt3Eyilkl8ZreDbzDMbnl1a/n58MJvBzPvCnQgR1jjF+gJ0WheUB4I6m4z6Zzt5QTsrgnEsrKnFNrAoSbdCZxhcbaLB2a/2SmRQNPS5k5AX2L6gY3WshHl/VUWXciAW7WvkH0+ne0V9nUQX9VMeH6skIqB383rwnC5OsQvTQVp+DmpRRiGd8BCE3C0nRz/UeYffGc2tuY58AWVjBDoAAYAa081M+Zdp/wJei9iuj2F1DC9fOyfTMBZezsy1B3uwIvL3bCA1QnnmiGkwmopgyLf4V9plkf+ZcpmWx6PeF50wMatBI6JVRZOPAKASee3ocYhSfQlbCoo0DAU9q2J22liPRNW2A0dqmVeN5LZi+StYamT2NZnieeqYS88ij6vqTMF9TNhZm5R3StB9cYh5U+Q1w+NUeFskFpxe9VXIfm3/t/IIum16cr8roYhN9Kpza0iiff3RTuEl2Yz0dxOBBsbUzqZkmi+orMZCbJymRjuHoVxU9dOvUOEjUpHJy6gbWBS2dkys/wxIDOiUQagln2NAgOj3ezYso0bhkM=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/BadIPs.com_KEY
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - sudo apt-get -y install python3-pip
  - sudo apt-get -y install dos2unix
  - pip3 install colorama

script:
  - export TRAVIS_BUILD_DIR=${TRAVIS_BUILD_DIR}
  - export GH_TOKEN=${GH_TOKEN}
  - export TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG}
  - export GIT_BRANCH=${GIT_BRANCH}
  - export GIT_EMAIL=${GIT_EMAIL}
  - export GIT_NAME=${GIT_NAME}
  - python3 ./update.py

notifications:
  email: false
