env:
  global:
    - secure: gTWjKSd/Vk1eDAHFi0VpZFFaBaIVOohArfynHbqw/S0bn9gu8H8SO9062MLW5SXvw+1ynXGFRLxG1VEOP6TMugxw44LevP7eXK9bbjv2Lgw0ZUJ8rF+PPe9H/wccAdhaY5YGSMrveJpQAoeSn1AHfH83WFHXxksdP0/CIuF0ZjcY7wwE+hSKQMnWPBnZyJRwOkd//1PPaG740wMxBtUqpZq83cO02FqdWTKc+2enUoJI0T7BcJXrZzGgNFyZsQgMWAOljwfy1EDofE7T0XtvQPROSU2g0VHxiG+XrWRjxY8bV5r7tAFfSbhVTj6ZtwYbnR8Km5vFer8t14SWO9u0nEaUreYE/QmAuUKxFayVKTQkvCCg15Q8WTFFtHbA+ejahXhS9hjW9ODXlUSbrznf3hEnhvjWRcJhMdXkXXVjx41g+CPjl1W1lhIlEyNQK7SjyFgL7bGM4QxYqWkFwoTQ7J7M+ILXFMUlTpsjlRDrqgBTY0c4LFDfnAaIzfe1aphMVoc5/ZTPNX8pv+Fa4qLNdrGkU6DMi00fXECs0u0oEgQ+Ms+jF2Sb8qM8yrCmu2faJq41yop6M4ug4omBitjcl06K+qnYe8yL3qJDJsQaSXfPDUYXkYOWRij+k/N/zZOdmQ9pSFnMoVVg4c4qI6pBT5xVsxn0O7g8uspmPPEnwF8=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/BadIPs.com_KEY
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
